app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('national-card/', views.nationalCard, name="national_card"),
    path('passport/', views.passport, name="passport"),
    path('car-license/', views.carLicense, name="car_license"),
    path('car-violation/', views.carViolation, name="car_violation"),
    path('check/', views.check, name="check"),
]

counter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def login(request):
    return render(request, "app/login.html", context=None)
def nationalCard(request):
    return render(request, "app/nationalCard.html", context=None)
def passport(request):
    return render(request, "app/passport.html", context=None)
def carLicense(request):
    return render(request, "app/carLicense.html", context=None)
def carViolation(request):
    return render(request, "app/carViolation.html", context=None)
def check(request):
    return render(request, "app/check.html", context=None)

templates/app/carLicense.html
{% extends 'template.html' %}


{% block content %}
<main class="main">
  
    <br><br>
    <form action="#" method="post" target="_blank">
        <h2>ثبت نام کارت ملی</h2>
        <div class="clearfix">
            <div class="col-25">
                <label for="fname">بارگذاری تصویر</label>
            </div>
            <div class="col-75">
                <div class="avatar-upload">
                    <div class="avatar-edit">
                        <input type='file' id="imageUpload" accept=".png, .jpg, .jpeg" />
                        <label for="imageUpload" title="بارگذاری تصویر"></label>
                    </div>
                    <div class="avatar-preview">
                        {% load static %}
                        <div id="imagePreview" style="background-image: url('{% static 'img/default.png' %}')">
                        </div>
                    </div>
                </div>
                <ul>
                    <li>عکس باید اینجوری باشد</li>
                    <li>عکس باید اونجوری باشد</li>
                </ul>

            </div>
        </div>
    
        <div class="clearfix">
    
            <div class="col-25">
                <label for="fname">نام</label>
            </div>
            
            <div class="col-75">
                <input id="fname" type="text" name="fname" placeholder=" نام" required>
            </div>
        </div>

        
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">نام خانوادگی</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" placeholder="نام خانوادگی" required>
            </div>
        </div>
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">تاریخ تولد</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" class="example1" placeholder="تاریخ تولد" required>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="email">ایمیل</label>
            </div>
            
            <div class="col-75">
                <input id="email" type="email" name="email" placeholder="ایمیل" required>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="subject">استان</label>
            </div>
            
            <div class="col-75">
                <select id="subject" name="subject" required>
                    <option value="work" disabled selected>استان</option>
                    <option value="work">همدان</option>
                    <option value="help">تهران</option>
                    <option value="general">سیستان</option>
                </select>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="message">آدرس</label>
            </div>
            
            <div class="col-75">
                <textarea id="message" name="message" placeholder="آدرس" required></textarea>
            </div>
        </div>
        
        <div class="clearfix">
            <div>
                <input type="submit" value="ثبت">
            </div>
        </div>
        
    </form>


</main>


{% endblock content %}
    

templates/app/check.html
{% extends 'template.html' %}


{% block content %}
<main class="main">
  
    <br><br>
    <form action="#" method="post" target="_blank">
        <!-- <h2>ثبت نام کارت ملی</h2> -->
        <h2>پیگیری وضعیت کارت ملی</h2>
        <div class="clearfix">
    
            <div class="col-25">
                <label for="fname">کد ملی متقاضی</label>
            </div>
            
            <div class="col-75">
                <input id="fname" type="text" name="fname" placeholder=" کد ملی متقاضی" required>
            </div>
        </div>

        
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">شماره پیگیری</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" placeholder="شماره پیگیری" required>
            </div>
        </div>
    
        <div class="clearfix">
            <div>
                <input type="submit" value="جستوجو">
            </div>
        </div>
        
    </form>


</main>


{% endblock content %}
    

templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/login.css' %}">

    <title>Login</title>

</head>
<body>
    <div class="login">
        <h3>ورود به سامانه پیشخوان</h3>
        <form method="post">
            <input type="text" name="u" placeholder="نام کاربری" required="required" />
            <input type="password" name="p" placeholder="گذرواژه" required="required" />
            <button type="submit" class="btn btn-primary btn-block btn-large">ورود</button>
        </form>
    </div>
</body>
</html>

templates/app/nationalCard.html
{% extends 'template.html' %}


{% block content %}
<main class="main">
  
    <br><br>
    <form action="#" method="post" target="_blank">
        <h2>ثبت نام کارت ملی</h2>
        <div class="clearfix">
            <div class="col-25">
                <label for="fname">بارگذاری تصویر</label>
            </div>
            <div class="col-75">
                <div class="avatar-upload">
                    <div class="avatar-edit">
                        <input type='file' id="imageUpload" accept=".png, .jpg, .jpeg" />
                        <label for="imageUpload" title="بارگذاری تصویر"></label>
                    </div>
                    <div class="avatar-preview">
                        {% load static %}
                        <div id="imagePreview" style="background-image: url('{% static 'img/default.png' %}')">
                        </div>
                    </div>
                </div>
                <ul>
                    <li>عکس باید اینجوری باشد</li>
                    <li>عکس باید اونجوری باشد</li>
                </ul>

            </div>
        </div>
    
        <div class="clearfix">
    
            <div class="col-25">
                <label for="fname">نام</label>
            </div>
            
            <div class="col-75">
                <input id="fname" type="text" name="fname" placeholder=" نام" required>
            </div>
        </div>

        
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">نام خانوادگی</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" placeholder="نام خانوادگی" required>
            </div>
        </div>
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">تاریخ تولد</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" class="example1" placeholder="تاریخ تولد" required>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="email">ایمیل</label>
            </div>
            
            <div class="col-75">
                <input id="email" type="email" name="email" placeholder="ایمیل" required>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="subject">استان</label>
            </div>
            
            <div class="col-75">
                <select id="subject" name="subject" required>
                    <option value="work" disabled selected>استان</option>
                    <option value="work">همدان</option>
                    <option value="help">تهران</option>
                    <option value="general">سیستان</option>
                </select>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="message">آدرس</label>
            </div>
            
            <div class="col-75">
                <textarea id="message" name="message" placeholder="آدرس" required></textarea>
            </div>
        </div>
        
        <div class="clearfix">
            <div>
                <input type="submit" value="ثبت">
            </div>
        </div>
        
    </form>


</main>


{% endblock content %}
    

templates/app/passport.html
{% extends 'template.html' %}


{% block content %}
<main class="main">
  
    <br><br>
    <form action="#" method="post" target="_blank">
        <h2>ثبت نام کارت ملی</h2>
        <div class="clearfix">
            <div class="col-25">
                <label for="fname">بارگذاری تصویر</label>
            </div>
            <div class="col-75">
                <div class="avatar-upload">
                    <div class="avatar-edit">
                        <input type='file' id="imageUpload" accept=".png, .jpg, .jpeg" />
                        <label for="imageUpload" title="بارگذاری تصویر"></label>
                    </div>
                    <div class="avatar-preview">
                        {% load static %}
                        <div id="imagePreview" style="background-image: url('{% static 'img/default.png' %}')">
                        </div>
                    </div>
                </div>
                <ul>
                    <li>عکس باید اینجوری باشد</li>
                    <li>عکس باید اونجوری باشد</li>
                </ul>

            </div>
        </div>
    
        <div class="clearfix">
    
            <div class="col-25">
                <label for="fname">نام</label>
            </div>
            
            <div class="col-75">
                <input id="fname" type="text" name="fname" placeholder=" نام" required>
            </div>
        </div>

        
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">نام خانوادگی</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" placeholder="نام خانوادگی" required>
            </div>
        </div>
        <div class="clearfix">
            <div class="col-25">
                <label for="lname">تاریخ تولد</label>
            </div>
            
            <div class="col-75">
                <input id="lname" type="text" name="lname" class="example1" placeholder="تاریخ تولد" required>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="email">ایمیل</label>
            </div>
            
            <div class="col-75">
                <input id="email" type="email" name="email" placeholder="ایمیل" required>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="subject">استان</label>
            </div>
            
            <div class="col-75">
                <select id="subject" name="subject" required>
                    <option value="work" disabled selected>استان</option>
                    <option value="work">همدان</option>
                    <option value="help">تهران</option>
                    <option value="general">سیستان</option>
                </select>
            </div>
        </div>
        
        <div class="clearfix">
            <div class="col-25">
                <label for="message">آدرس</label>
            </div>
            
            <div class="col-75">
                <textarea id="message" name="message" placeholder="آدرس" required></textarea>
            </div>
        </div>
        
        <div class="clearfix">
            <div>
                <input type="submit" value="ثبت">
            </div>
        </div>
        
    </form>


</main>


{% endblock content %}
    

templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/persian-datepicker.css' %}"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>Document</title>
</head>
<body>
    
    <div class="grid">

        <header class="header">
  
          <i id="menu_toggle" class="fas fa-bars header__menu"></i>
  
        </header>
  
          <aside class="sidenav">
            <div class="sidenav__brand">
                  <a href="#">پیشخوان خدمات دولت </a>
                  <i class="fas fa-times sidenav__brand-close"></i>
              
            </div>
            <div class="sidenav__profile">
              <div class="sidenav__profile-avatar"></div>
              <div class="sidenav__profile-title text-light">اوپراتور ۱۲۳</div>
            </div>
            <div class="row row--align-v-center row--align-h-center">
              <ul class="navList">
                <li class="navList__heading">کارت ملی<i class="fa fa-id-card"></i></li>
                <li>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:national_card' %}"> ثبت نام</a></span>
                  </div>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:check' %}"> استعلام</a></span>
                  </div>
              </li>
              
              <li class="navList__heading">گذرنامه<i class="fas fa-passport"></i></li>
                <li>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:passport' %}"> ثبت نام</a></span>
                  </div>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:check' %}"> استعلام</a></span>
                  </div>
              </li>
              
  
              <li class="navList__heading">گواهینامه<i class="far fa-certificate" aria-hidden="true"></i></li>
                <li>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:car_license' %}"> ثبت نام</a></span>
                  </div>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:check' %}"> استعلام</a></span>
                  </div>
              </li>
              
  
              <li class="navList__heading">خلافی خودرو<i class="far fa-car"></i></li>
                <li>
                  <div class="item-title">
                    <span class="navList__subheading-title"><a href="{% url 'app:check' %}"> استعلام</a></span>
                  </div>
              </li>
              <br><br>
              <hr>
              <br>
              <li class="exit_item" >
                خروج<i class="fa fa-sign-out"></i>
              </li>
  
  
              <div class="footer">
                  <p>صادق ایپکی جو</p><br>
                  <p>مصطفی مرادی</p><br>
              </div>
          </ul>
          </div>
  
          </aside>
  

        {% block content %}{% endblock content %}
          <!-- <footer class="footer">
            <p><span class="footer__copyright">&copy;</span> 2018 MTH</p>
            <p>Crafted with <i class="fas fa-heart footer__icon"></i> by <a href="https://www.linkedin.com/in/matt-holland/" target="_blank" class="footer__signature">Matt H</a></p>
          </footer> -->
    </div> 
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      {% load static %}
	  <script src="{% static 'js/persian-date.js' %}"></script>
	  <script src="{% static 'js/persian-datepicker.js' %}"></script>
	  <script language="JavaScript" type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>